INSERT INTO questions (qid, topic, subtopic, question, question_image, options, option_images, correct_index, correct_indices, explanation, difficulty, group_number, correct_count, total_count, consecutive_correct, last_answered_at, next_review_at, interval_days) VALUES
('Q312', 'Parcial 1', 'General', '¿Cuál de las siguientes afirmaciones con respecto a TCP/IP es correcta?', '', ARRAY['TCP/IP combina las cuatro capas inferiores del modelo OSI en una sola capa, la capa de internet','TCP/IP combina las capas 2 y 3 del modelo OSI en una sola capa','TCP/IP combina las funciones de la capa de enlace de datos y de sesión','Ninguna de las opciones disponibles'], NULL, 3, ARRAY[3], 'Pregunta del Parcial 1', 'medium', 20, 0, 0, 0, NULL, now(), 1),
('Q313', 'Parcial 1', 'General', 'La efectividad del sistema de transmisión de datos depende de 4 características fundamentales. ¿Cuál de las siguientes opciones NO es una de estas características?', '', ARRAY['Puntualidad','Entrega','Topología','Exactitud','Retardo variable'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q314', 'Parcial 1', 'General', '¿Cuál es la forma reducida (comprimida) de la siguiente dirección IPv6: 2001:0db8:1234:1100:0000:0000:0000:00ff?', '', ARRAY['2001:db8:1234:1100::ff','2001:db8:1234:1100:0:0:0:ff','2001:0db8:1234:11::ff','2001:db8:1234::00ff'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'medium', 20, 0, 0, 0, NULL, now(), 1),
('Q315', 'Parcial 1', 'General', 'Un técnico de soporte acaba de llegar a una empresa y le preguntan cuál es el dispositivo que conecta múltiples redes y elige la mejor ruta para enviar los paquetes entre ellas. ¿Cuál es ese dispositivo?', '', ARRAY['Switch','Hub','Router','Access Point','Bridge'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q316', 'Parcial 1', 'General', 'El administrador de red de una PYME necesita explicarle a su jefe qué es el ancho de banda. ¿Cuál de las siguientes definiciones es la más precisa?', '', ARRAY['La velocidad a la que viajan los bits por el medio físico','La cantidad de datos que pueden transmitirse en un período de tiempo determinado','El retardo que experimenta un paquete al atravesar la red','El número máximo de dispositivos conectados a una red','La distancia máxima de un cable de red'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q317', 'Parcial 1', 'General', 'Un estudiante conecta su laptop a un switch de 24 puertos en el laboratorio. ¿En qué capa del modelo OSI opera principalmente un switch gestionado?', '', ARRAY['Capa 1 - Física','Capa 2 - Enlace de datos','Capa 3 - Red','Capa 4 - Transporte','Capa 7 - Aplicación'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q318', 'Parcial 1', 'General', '¿Cuál de los siguientes medios de transmisión es completamente inmune a las interferencias electromagnéticas (EMI)?', '', ARRAY['Cable UTP Cat6','Cable coaxial','Cable STP','Fibra óptica','Cable par trenzado'], NULL, 3, ARRAY[3], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q319', 'Parcial 1', 'General', 'Un ingeniero de redes necesita acceder a la CLI de un switch Cisco recién adquirido (sin configuración previa). ¿Qué tipo de conexión física debe usar obligatoriamente?', '', ARRAY['Conexión SSH por red','Conexión Telnet por red','Puerto de consola con cable rollover','Puerto USB tipo A','Conexión WiFi por defecto'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q320', 'Parcial 1', 'General', '¿Cuál es el comando correcto para entrar al modo de configuración global en un dispositivo Cisco IOS desde el modo EXEC privilegiado?', '', ARRAY['enable','configure terminal','interface fastethernet 0/0','show running-config','login'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q321', 'Parcial 1', 'General', 'Un administrador desea ver la configuración activa de un switch Cisco en tiempo real. ¿Cuál es el comando que debe ejecutar?', '', ARRAY['show startup-config','show running-config','show version','show interfaces','display config'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q322', 'Parcial 1', 'General', '¿Cuál de los siguientes protocolos resuelve nombres de dominio a direcciones IP?', '', ARRAY['DHCP','ARP','DNS','NAT','ICMP'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q323', 'Parcial 1', 'General', 'En el modelo TCP/IP, ¿cuál capa es equivalente a las capas de Sesión, Presentación y Aplicación del modelo OSI combinadas?', '', ARRAY['Capa de Acceso a la red','Capa de Internet','Capa de Transporte','Capa de Aplicación','No existe equivalente'], NULL, 3, ARRAY[3], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q324', 'Parcial 1', 'General', '¿Qué tipo de cable se debe usar para conectar directamente dos switches Cisco entre sí (sin usar Auto-MDIX)?', '', ARRAY['Cable directo (straight-through)','Cable cruzado (crossover)','Cable rollover (consola)','Cable coaxial','Cualquiera de los anteriores'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q325', 'Parcial 1', 'General', 'Un administrador ejecuta el siguiente bloque en un switch Cisco:

Switch(config)# banner motd # Acceso restringido. Solo personal autorizado. #

¿En qué momento exacto se mostrará este mensaje a un usuario?', '', ARRAY['Solo cuando el usuario ejecuta ''show banner''','Antes de que el usuario introduzca sus credenciales de login','Solo después de autenticarse exitosamente','Al ejecutar ''show version''','Solo en conexiones por consola, no por SSH'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q326', 'Parcial 1', 'General', 'Un técnico configura un switch con los siguientes comandos:
Switch(config)# enable secret Cisco123
Switch(config)# enable password cisco

¿Cuál contraseña es efectiva para acceder al modo EXEC privilegiado y por qué?', '', ARRAY['Cisco123, porque ''enable secret'' tiene prioridad sobre ''enable password'' y usa MD5','cisco, porque fue configurada después','Ambas funcionan en diferentes turnos','Ninguna, se requiere configurar ''service password-encryption''','cisco, porque ''enable password'' es más reciente en el estándar IOS'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q327', 'Parcial 1', 'General', '¿Cuáles de los siguientes comandos forman la secuencia CORRECTA y COMPLETA para asignar una contraseña encriptada a las líneas VTY (0 a 4) de un switch Cisco y habilitar el login? (Selecciona tres)', '', ARRAY['Switch(config)# line vty 0 4','Switch(config-line)# password Redes2024','Switch(config-line)# login','Switch(config)# service password-encryption','Switch(config-line)# enable secret Redes2024','Switch(config)# ip ssh version 2'], NULL, 0, ARRAY[0,1,2], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q328', 'Parcial 1', 'General', 'Un administrador de red observa que al ejecutar ''show running-config'' las contraseñas aparecen en texto claro. ¿Qué comando global soluciona esto para TODAS las contraseñas de tipo 0 y tipo 7?', '', ARRAY['Switch(config)# enable secret password','Switch(config)# service password-encryption','Switch(config)# encrypt all passwords','Switch(config)# password-hash md5','Switch(config)# security passwords min-length 8'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q329', 'Parcial 1', 'General', 'Observa la siguiente secuencia de comandos en un switch Cisco:
Switch# copy running-config startup-config

¿Cuál es el propósito específico de este comando y qué ocurriría si NO se ejecutara antes de un reinicio?', '', ARRAY['Guarda la config de RAM a NVRAM; sin ejecutarlo, los cambios se perderán al reiniciar','Copia la config de NVRAM a RAM; sin ejecutarlo el switch no arranca','Guarda la config en un servidor TFTP; sin ejecutarlo no hay respaldo','Restaura la configuración de fábrica; sin ejecutarlo el switch mantiene los cambios','Sincroniza la config entre switches; no tiene efecto en reinicios'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q330', 'Parcial 1', 'General', 'Un ingeniero analiza el tráfico de red y observa que la PDU en la Capa 2 contiene las siguientes cabeceras: dirección MAC destino (FF:FF:FF:FF:FF:FF), MAC origen (A4:B1:C2:D3:E4:F5) y tipo 0x0806. ¿Qué tipo de tráfico está analizando?', '', ARRAY['Una solicitud DHCP en broadcast','Una solicitud ARP buscando la MAC de una IP destino','Un paquete ICMP (ping) en broadcast','Una trama de Spanning Tree Protocol','Un anuncio de router (Router Advertisement)'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1),
('Q331', 'Parcial 1', 'General', '¿Cuáles son las DOS capas del modelo OSI que el modelo TCP/IP agrupa en su capa de ''Acceso a la Red''? (Selecciona dos)', '', ARRAY['Capa Física (1)','Capa de Enlace de datos (2)','Capa de Red (3)','Capa de Transporte (4)','Capa de Sesión (5)','Capa de Presentación (6)'], NULL, 0, ARRAY[0,1], 'Pregunta del Parcial 1', 'hard', 20, 0, 0, 0, NULL, now(), 1);