INSERT INTO questions (qid, topic, subtopic, question, question_image, options, option_images, correct_index, correct_indices, explanation, difficulty, group_number, correct_count, total_count, consecutive_correct, last_answered_at, next_review_at, interval_days) VALUES
('Q332', 'Parcial 1', 'General', 'Una empresa tiene 3 departamentos: Ventas (30 hosts), TI (15 hosts) y Gerencia (10 hosts), todos en la red 192.168.1.0/24. El administrador quiere segmentar por departamento pero los equipos de un mismo departamento deben comunicarse sin pasar por el router. ¿Qué tecnología de capa 2 permite esta segmentación lógica dentro de un mismo switch físico?', '', ARRAY['NAT (Network Address Translation)','VLAN (Virtual LAN)','STP (Spanning Tree Protocol)','OSPF (Open Shortest Path First)','QoS (Quality of Service)'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q333', 'Parcial 1', 'General', 'Un host envía un paquete a 192.168.1.255 estando en la red 192.168.1.0/24. ¿Qué tipo de comunicación es esta y a quiénes llega el mensaje?', '', ARRAY['Unicast, solo llega al host 192.168.1.255','Broadcast dirigido, llega a todos los hosts de la red 192.168.1.0/24','Multicast, llega a un grupo específico de suscriptores','Broadcast limitado, llega a todos los dispositivos de Internet','Anycast, llega al host más cercano con esa IP'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q334', 'Parcial 1', 'General', '¿Cuáles de las siguientes afirmaciones sobre TCP vs UDP son correctas? (Selecciona dos)', '', ARRAY['TCP garantiza la entrega ordenada de datos mediante números de secuencia y acuses de recibo (ACK)','UDP es más confiable que TCP porque no pierde paquetes','UDP es preferido para streaming de video en tiempo real por su menor sobrecarga','TCP usa el proceso de 3-way handshake: SYN, SYN-ACK, ACK','UDP establece conexión antes de enviar datos igual que TCP','TCP opera en la capa de Red del modelo OSI'], NULL, 0, ARRAY[0,2], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q335', 'Parcial 1', 'General', 'Un administrador configura el siguiente bloque en un switch de acceso:

Switch(config)# hostname SW-PISO3
SW-PISO3(config)# ip domain-name empresa.local
SW-PISO3(config)# crypto key generate rsa modulus 2048
SW-PISO3(config)# ip ssh version 2
SW-PISO3(config)# username admin privilege 15 secret Admin@2024
SW-PISO3(config)# line vty 0 4
SW-PISO3(config-line)# transport input ssh
SW-PISO3(config-line)# login local

¿Cuál sería el impacto si se omite el comando ''ip domain-name empresa.local'' de esta secuencia?', '', ARRAY['SSH funcionaría igualmente; el dominio solo es para DNS','No se podría generar el par de claves RSA, por lo que SSH no podría habilitarse','Las líneas VTY no aceptarían conexiones de ningún tipo','El hostname no se aplicaría correctamente','Solo afectaría las conexiones Telnet, no SSH'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q336', 'Parcial 1', 'General', 'Un técnico analiza el siguiente escenario: Host A (192.168.10.5/24) necesita enviar datos a Host B (192.168.20.8/24). Ambos están separados por un router con interfaces Gi0/0 (192.168.10.1/24) y Gi0/1 (192.168.20.1/24). Al analizar la trama que sale de Host A hacia el router, ¿cuáles son las direcciones MAC de origen y destino CORRECTAS en esa trama?', '', ARRAY['Origen: MAC de Host A | Destino: MAC de Host B','Origen: MAC de Host A | Destino: MAC de la interfaz Gi0/0 del router','Origen: MAC del router Gi0/0 | Destino: MAC de Host B','Origen: MAC de Host A | Destino: Broadcast FF:FF:FF:FF:FF:FF','Origen: MAC de Host A | Destino: MAC de la interfaz Gi0/1 del router'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q337', 'Parcial 1', 'General', '¿Cuáles de los siguientes son componentes de la PDU de la Capa 4 (Transporte) cuando se usa TCP? (Selecciona tres)', '', ARRAY['Número de puerto de origen','Número de secuencia','Dirección IP de destino','Bit de control ACK/SYN','Dirección MAC de origen','TTL (Time To Live)'], NULL, 0, ARRAY[0,1,3], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q338', 'Parcial 1', 'General', 'Un administrador ejecuta ''show interfaces fastethernet 0/1'' y observa: ''FastEthernet0/1 is up, line protocol is down''. ¿Qué indica EXACTAMENTE este estado y cuál es la causa más probable?', '', ARRAY['La interfaz física tiene conectividad pero el protocolo de capa 2 no está operativo; causa probable: problema de encapsulación o keepalives','La interfaz está físicamente desconectada y sin cable','La interfaz fue apagada con ''shutdown'' por el administrador','Hay un problema de duplex mismatch en capa 1','El STP bloqueó la interfaz para evitar bucles'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q339', 'Parcial 1', 'General', 'Una empresa implementa el siguiente banner en todos sus dispositivos Cisco:
Switch(config)# banner motd $
ATENCIÓN: Este sistema es EXCLUSIVAMENTE para uso autorizado.
El acceso no autorizado será perseguido legalmente.
$

¿Cuál es la importancia legal de configurar este banner ANTES de implementar medidas de seguridad de login?', '', ARRAY['No tiene importancia legal; es solo informativo para los administradores','Sin banner previo, en muchas jurisdicciones legales no se puede perseguir penalmente el acceso no autorizado por falta de aviso explícito','El banner reemplaza la necesidad de contraseñas de acceso','Solo es necesario en dispositivos con acceso físico, no en acceso remoto','Cisco requiere el banner para activar las licencias de IOS'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q340', 'Parcial 1', 'General', 'Al comparar el modelo OSI con el modelo TCP/IP, ¿cuáles de las siguientes afirmaciones son CORRECTAS? (Selecciona tres)', '', ARRAY['El modelo OSI tiene 7 capas; el modelo TCP/IP tiene 4 capas','La capa de Transporte existe en ambos modelos con funciones equivalentes','TCP/IP fue desarrollado primero como modelo teórico; OSI surgió después como implementación práctica','La capa de Internet del modelo TCP/IP corresponde a la capa de Red (capa 3) del modelo OSI','OSI fue diseñado como modelo de referencia teórico; TCP/IP surgió de la implementación práctica de ARPANET','Ambos modelos tienen exactamente las mismas capas con diferente nomenclatura'], NULL, 0, ARRAY[0,1,3], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q341', 'Parcial 1', 'General', 'Un administrador revisa el proceso completo de encapsulación TCP/IP. Coloca los datos en el orden CORRECTO de encapsulación cuando un usuario envía un email (de la capa más alta a la más baja):', '', ARRAY['Datos → Segmento → Paquete → Trama → Bits','Bits → Trama → Paquete → Segmento → Datos','Trama → Paquete → Segmento → Datos → Bits','Datos → Paquete → Segmento → Trama → Bits','Segmento → Datos → Paquete → Bits → Trama'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q342', 'Parcial 1', 'General', 'Un administrador configura un switch Cisco con:
SW(config)# line console 0
SW(config-line)# exec-timeout 5 30

¿Qué efecto tiene exactamente el comando ''exec-timeout 5 30''?', '', ARRAY['La sesión de consola expira después de 5 minutos y 30 segundos de inactividad','La sesión expira a los 5 horas y 30 minutos','El dispositivo se reinicia automáticamente si no hay actividad en 5 segundos y 30 milisegundos','Se permiten máximo 5 conexiones simultáneas con timeout de 30 segundos','La contraseña expira cada 5 meses y 30 días'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q343', 'Parcial 1', 'General', 'Un ingeniero analiza el siguiente escenario de subnetting: La red 172.16.0.0/16 debe dividirse para dar soporte a 5 subredes, cada una con al menos 1000 hosts utilizables. ¿Cuál es la máscara de subred correcta y cuántos hosts utilizables tiene cada subred?', '', ARRAY['255.255.248.0 (/21) — 2046 hosts utilizables por subred','255.255.252.0 (/22) — 1022 hosts utilizables por subred','255.255.254.0 (/23) — 510 hosts utilizables por subred','255.255.255.0 (/24) — 254 hosts utilizables por subred','255.255.240.0 (/20) — 4094 hosts utilizables por subred'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q344', 'Parcial 1', 'General', 'Durante el proceso de arranque de un switch Cisco, ¿cuál es el orden correcto de los eventos de inicio del IOS?', '', ARRAY['POST → Cargar Bootstrap → Buscar y cargar IOS → Cargar startup-config','Cargar IOS → POST → Bootstrap → Cargar startup-config','Cargar startup-config → POST → IOS → Bootstrap','Bootstrap → Cargar startup-config → POST → IOS','POST → Cargar startup-config → Bootstrap → IOS'], NULL, 0, ARRAY[0], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q345', 'Parcial 1', 'General', '¿Cuáles de las siguientes son características que diferencian IPv6 de IPv4? (Selecciona tres)', '', ARRAY['IPv6 tiene un espacio de direcciones de 128 bits frente a los 32 bits de IPv4','IPv6 usa NAT de forma obligatoria para conservar direcciones','IPv6 incluye autoconfiguración de direcciones sin servidor DHCP (SLAAC)','IPv6 elimina la necesidad del checksum en la cabecera IP para mayor eficiencia','IPv6 usa ARP para resolver direcciones MAC igual que IPv4','IPv6 mantiene la misma longitud de cabecera que IPv4 (20 bytes)'], NULL, 0, ARRAY[0,2,3], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q346', 'Parcial 1', 'General', 'Un administrador debe asegurar el acceso a la línea de consola de todos los switches de la empresa. Analiza la siguiente configuración:

SW(config)# line console 0
SW(config-line)# password Consola2024
SW(config-line)# login
SW(config-line)# logging synchronous
SW(config-line)# exec-timeout 3 0

¿Cuál es el propósito específico de ''logging synchronous'' en esta configuración?', '', ARRAY['Sincroniza los logs con un servidor Syslog externo','Evita que los mensajes de log del sistema interrumpan e ilegibilicen los comandos que está escribiendo el administrador','Activa el registro de todos los comandos ejecutados por el usuario','Sincroniza el reloj del dispositivo con NTP','Habilita la transmisión de logs en tiempo real por SSH'], NULL, 1, ARRAY[1], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q347', 'Parcial 1', 'General', 'Una empresa de telecomunicaciones debe conectar 3 edificios separados 8 km entre sí con un enlace de alta velocidad y alta seguridad ante interferencias. El presupuesto permite una solución profesional. ¿Qué combinación de medio físico y dispositivo de interconexión es la más adecuada?', '', ARRAY['Cable UTP Cat6A con switches de acceso en cada edificio','Cable coaxial con repetidores cada 500 metros','Fibra óptica monomodo con switches de capa 3 o routers con interfaces de fibra','Enlace inalámbrico 5GHz con access points directivos','Cable STP blindado con amplificadores de señal'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1),
('Q348', 'Parcial 1', 'General', 'Un estudiante de CCNA analiza el siguiente escenario complejo: Un paquete con IP destino 10.0.0.50 llega a un router con la siguiente tabla de enrutamiento:
• 10.0.0.0/8 via Gi0/0
• 10.0.0.0/16 via Gi0/1
• 10.0.0.0/24 via Gi0/2
• 0.0.0.0/0 via Gi0/3 (ruta por defecto)

¿Por cuál interfaz reenvía el router el paquete y por qué principio?', '', ARRAY['Gi0/0, porque es la primera ruta en la tabla','Gi0/3, porque la ruta por defecto tiene la mayor prioridad','Gi0/2, porque se aplica el principio de ''Longest Prefix Match'' (coincidencia del prefijo más largo)','Gi0/1, porque /16 es un balance entre especificidad y generalidad','El paquete se descarta por ambigüedad en la tabla de enrutamiento'], NULL, 2, ARRAY[2], 'Pregunta del Parcial 1', 'hard', 21, 0, 0, 0, NULL, now(), 1);